# Generated by Django 5.1.4 on 2025-03-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='user name')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='age')),
            ],
        ),
    ]
