# Generated by Django 5.1.4 on 2025-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='削除'),
        ),
    ]
