# Generated by Django 5.1.4 on 2025-03-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_member_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
    ]
